version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3030
    volumes:
      - data:/var/lib/mysql

  bedrock:
    build:
      context: .
      dockerfile: ./build/bedrock.dockerfile
    container_name: bedrock
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge_public"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=le"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"    
    links:
      - mariadb
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./bedrock:/srv/bedrock

volumes:
  data:
